### ISSUE TITLE
Feature observation series report

### ISSUE THREAD

**Issue by mingfeng** [City-of-Helsinki/ltj#117]
Create Feature observation series report that similar to: https://kartta.hel.fi/applications/ltj/reports/lajihavainnot.aspx?ID=437&luokka=Arvokkaat+kasvillisuus-+ja+kasvistokohteet&aluokka=

Feature report should contains a link to the feature observation series report.

**Comment by frwickst** [comment]
@mingfeng The page linked here is not of an observation series, but of all species that has been found at a specific location.
Feature: https://kartta.hel.fi/applications/ltj/reports/kohderaportti.aspx?id=437
Observation:  https://kartta.hel.fi/applications/ltj/reports/lajihavainnot.aspx?id=437
Observation series: https://kartta.hel.fi/applications/ltj/reports/havaintosarjat.aspx?id=437

The ID in all of these cases seem to be a feature and not the id of a specific instance of the given model
