### ISSUE TITLE
(Testataan myöhemmin) Authentication / Report filtering

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#160]
A) Report versions. Filtering in these is not tested, because is not possible yet. Sanna will test when possible. 
- Public
- Officer
- Officer Helsinki
- Admin

B) In species report filtering there is a mixing between public and open data (?) Now "only **open** data is displayed to non-staff users", but **public** data is the one that should be displayed. So in public report filtering field LUOKKA.WWW should be used; now LUOKKA.OPEN_DATA is used .     
https://github.com/City-Of-Helsinki/ltj/blob/master/nature/views.py
![image](https://user-images.githubusercontent.com/33342290/47996339-d8e5f980-e100-11e8-99e4-64e0ffa8d973.png)

**Comment by silenatte** [comment]
A) Vain Virkaversio_hki ei ole implementoitu.

B) 
```
Jos ymmärsin oikein, niin tämä www=True ei näy kirjautumattomalle käyttäjälle, mutta pitäisi näkyä:
https://ltj.dev.hel.ninja/ltj/feature-report/183702/

Kun taas tämä avoin_data=True näkyy kirjautumattomalle käyttäjälle, vaikkei pitäisi:
https://ltj.dev.hel.ninja/ltj/feature-report/135724/

Tämä voidaan ratkaista tekemällä FeatureClassQuerySet:iin toinen filtteri "www".
```

**Comment by SannaElijoki** [comment]
A) Hyvä.
Seuraavaksi, koska virkaversio_hki-käyttäjälle näytetään enemmän tietoa (myös UHEX-luokka) kuin virka-käyttäjälle (jolta UHEX-luokka suodatetaan pois), pitää tehdä näin:
Nyt "virkaversion" suodatuksilla olevista raporteista suodatetaan vielä UHEX-kohdeluokkaan kuuluvien kohteiden tiedot pois. Ja tehdään "virkaversio_hki"-raportit, joissa se puolestaan on.
_tai_ nimetään nykyiset "virkaversio"-raportit "virkaversio_hki" -raporteiksi ja tehdään uusi suodatus "virkaversio", josta siis on se UHEX poistettu.
Itse en tiedä kummin päin tämä kannattaa tehdä.

**Comment by SannaElijoki** [comment]
B) 
>Jos ymmärsin oikein, niin tämä www=True ei näy kirjautumattomalle käyttäjälle, mutta pitäisi näkyä:
>https://ltj.dev.hel.ninja/ltj/feature-report/183702/
>Kun taas tämä avoin_data=True näkyy kirjautumattomalle käyttäjälle, vaikkei pitäisi:
>https://ltj.dev.hel.ninja/ltj/feature-report/135724/
Juuri näin. Filtteriä kentän _open_data_ mukaan ei ole tarkoitus käyttää raporttipuolella lainkaan, vaan se on avoimen datan REST-rajapinnan suodatuksia varten. Yleisöversion raporteista pois suodatettavat kohdeluokat on määritelty _www_kentän avulla. 

Huom. tällä hetkellä näemmä sovelluksen käyttämän testitietokannan arvoissa näiden kenttien osalta on epäloogisia yhdistelmiä, eli moni kohdeluokka on määritelty www=false, mutta open_data=true. Muutan ne loogiseksi. Käytännössä siis näytämme yleisöversiossa tietyt aineistot, mutta koska jotkut niistä lähinnä kasviruutuaineistot ovat muiden aineistoa, emme voi julkaista niitä avoimena datana osaltamme.
![image](https://user-images.githubusercontent.com/33342290/48608867-b7e89880-e98b-11e8-95da-81aecc51ed4a.png)
