### ISSUE TITLE
LTJ-application / Feature form saving error

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#169]
9.1.2019 noticed error when saving feature form, for example https://ltj.dev.hel.ninja/ltj-dev/admin/nature/feature/15/change/ . Error comes every time when trying to save. Registers seem to work fine, maybe this is some geometry thing. 
This situation may have been few months now - application has not been tested/used in a while.
Haltu updated libraries https://requires.io/github/City-of-Helsinki/ltj/requirements/?branch=master in the beginning of November. They reported "because of drf-gis we have to settle for Djangon version 2.0." and "GeoDjangos `GeometryField`s one method LTJ is using is depricated". This was solved some way, but I did not realize to test feature form then. 

![image](https://user-images.githubusercontent.com/33342290/50892922-516e7c80-1408-11e9-91da-58982ce588d5.png)

**Comment by mingfeng** [comment]
I believe this is also fixed with package upgrades: #171

**Comment by SannaElijoki** [comment]
Unfortunately not.
