### ISSUE TITLE
Reports / Replacement text for filtered observations

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#176]
Sanna testaa kun eri roolien raportit testattavissa.

**Reports**: Officer user has to get information when data (observation in protection level 1 or any observation of protection level 1 species) is filtered out. In reports filtered observations will be replaced with "SALATTU HAVAINTO", like we have in old reports:

https://kartta.hel.fi/applications/ltj/reports/lajihavainnot.aspx?ID=135494
![image](https://user-images.githubusercontent.com/33342290/51233339-55ebe580-1972-11e9-897a-c340d0059c41.png)

(Public users will not get information when data is filtered out from their report).

**Comment by mingfeng** [comment]
@SannaElijoki Two question related to this:
- Do we **always** display this message to office users or only when there are filtered observations?
- Do we need to show this message in Species Report (Lajiraportti), where we also show a list of observations for target species?

**Comment by SannaElijoki** [comment]
@mingfeng 
- the message is displayed to office users only when there are filtered (level 1) observations. I´ll send you an example report. Notice that "Secret observation" -lines are listed to the end of the list. (so that secret species can´t be quessed by position in list)

- good point, we do need to show this message also in species report. I´ll send you an example of this, too
