### ISSUE TITLE
1. Ylimääräisen viivan poistaminen raportista

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#177]
Alla oleva alkuperäinen issue on tehty, mutta vielä pitäisi poistaa ylimääräinen viiva, joka tulee raporttiin tilanteessa jossa kohteella on kuvauskenttä, mutta kenttä 'text'/'text_www' on tyhjä.
![image](https://user-images.githubusercontent.com/33342290/52574500-1f946f80-2e25-11e9-8a09-5413496ea0a7.png)

---------------------------------
**TEHTY:**
Feature report: In KOHDEKUVAUS fields 'description' and 'text'/'text_www' are displayed. When 'description' is not empty but 'text'/'text_www' is, there is "None"-text in report. That should be removed. 

https://ltj.dev.hel.ninja/ltj-dev/ltj/feature-report/176797/

![image](https://user-images.githubusercontent.com/33342290/51235616-a6fed800-1978-11e9-9a7c-58611b105c3e.png)

**Comment by silenatte** [comment]
There is an unwanted line also under transactions. See /ltj/feature-report/135353/. I'd say let's fix this too.

**Comment by SannaElijoki** [comment]
Äsh, olin tulkinnut ylimääräisen viivan syyn väärin. Se on käytännössä raportin loppuosassa ennen footeria oleva viiva https://ltj.dev.hel.ninja/ltj-dev/ltj/feature-report/183686/  Toisaalta joistain blockeista puuttuu "oma" viiva, joten alimmaisen viivan poiston lisäksi pitää myös lisätä viivoja. Käyn nämä läpi vielä erikseen joten tässä välissä ei toimenpiteitä.

**Comment by SannaElijoki** [comment]
Suljen tämän. Asia on laitettu kohderaporttikommentteihin.
