### ISSUE TITLE
As an admin, I want to see the feature listing on a map and be able to select a feature to edit from the filtered/searched features on a map.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/ltj#18]
This is tricky in django-admin, as there is no readymade component for this.

Basically, implementing this would require javascript coding for drawing of the OSM map or, alternatively, a Leaflet map, overriding the standard django-admin list method. An idea for displaying points on a map in admin listing is shown here: https://stackoverflow.com/questions/32434998/geodjango-view-admin-list-view-on-a-map

Also, there seems to be a very WIP PR to django-leaflet that attempts the same: https://github.com/makinacorpus/django-leaflet/pull/124

**Comment by Rikuoja** [comment]
At any rate, this must be discussed later, before we decide if, when and how we will try to implement this :)

**Comment by Rikuoja** [comment]
Another option, of course, would be to actually try and finish the PR to django-leaflet, it has been open for two years now. Might be useful for more general use too.

**Comment by SannaElijoki** [comment]
Here is one example how #18 looks on GeoMedia now. The green feature (an important bird area) is picked to view and edit.
![18_example_from_geomedia](https://user-images.githubusercontent.com/33342290/32364269-869ab5a8-c07c-11e7-997a-0f523601726f.JPG)

**Comment by mingfeng** [comment]
I'm afraid our data size is more than a client side mapping tool can handle as vector geometries (i.e. let OpenLayers or Leaflet to draw feature geometry one by one). And IMHO, Django admin may not be the most suitable place to implement this kind of feature.

It seems to me that this is becoming more like a  WebGIS application feature , and I think we need a map rendering server here, which can publish the feature data as map services (e.g. WMS).

**Comment by Rikuoja** [comment]
Hm, how about displaying data by feature type? Then the amount of features (when zoomed in) is not too big?
