### ISSUE TITLE
Remove compiled translation from repository

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/ltj#191]
Repository contains a compiled translation (.mo), which tends to cause problems with git updates after translation are compiled. Git sees the compiled translation file as a changed file and refuses the pull in new code, when running non-interactively.

Seems that including it in repo serves no purpose and the file should be removed.

**Comment by silenatte** [comment]
Removed `pending review` tag for https://github.com/City-of-Helsinki/ltj/pull/192#issuecomment-467029525
