### ISSUE TITLE
1.  Suojeluarvoraportti / ei-voimassaolevien suojeluarvojen pois suodattaminen

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#195]
Suojeluarvoraportista suodatettava pois rivit, jotka koskevat säädöksiä joiden voimassa = false.
https://ltj.dev.hel.ninja/ltj-dev/ltj/species-regulations-report/8594/

Nyt raporttiin siis listaantuu myös ei-voimassaolevia, esim. tämän kaksi ensimmäistä:
![image](https://user-images.githubusercontent.com/33342290/52632341-f0840980-2ec9-11e9-9361-11f62a235fc1.png)

**Comment by SannaElijoki** [comment]
Ei-voimassaolevien suodatus ei toimi.

**Comment by otiala** [comment]
> Ei-voimassaolevien suodatus ei toimi.

Kyseistä Pull Requestia ei ole vielä mergetty masteriin. Pyydän Attea katselmoimaan ja mergeämään.

**Comment by SannaElijoki** [comment]
Ok, hyvä, että ei ollut jokin häikkä.
