### ISSUE TITLE
1 Raportit / none-kenttien näyttäminen

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#200]
_(Raporttien viilausta)_

A) Kohderaportti
https://ltj.dev.hel.ninja/ltj-dev/ltj/feature-report/743/
Kun kohteella ei ole nimeä, kentässä lukee NONE. Pitäisi muuttaa sellaiseksi, että feature.name (kohde.nimi)-kenttää ei näytetä, jos se on none. 
![image](https://user-images.githubusercontent.com/33342290/53077319-67d52100-34fa-11e9-9e2b-32db001bdce6.png)

B ) Lajiraportti
https://ltj.dev.hel.ninja/ltj-dev/ltj/species-report/11135/
Vastaava tilanne. Kenttä feature.name otsikoineen pitäisi muuttaa sellaiseksi, että niitä ei näytetä jos kohde.nimi on none.
![image](https://user-images.githubusercontent.com/33342290/53077892-b505c280-34fb-11e9-97b5-a811df455d7d.png)

C) Lajihavaintoraportti
https://ltj.dev.hel.ninja/ltj-dev/ltj/feature-observations-report/144677/  (huom. k.o. kohteen raportti aukeaa vain virka/admin-käyttäjälle, yleisöversion aineistossa ei ole tätä kohtaa koskevaa esimerkkiä)
- Kuvassa näkyvässä ylemmässä nonessa sama tilanne kuin A-kohdassa: Kun kohteella ei ole nimeä, kentässä lukee NONE. Pitäisi muuttaa sellaiseksi, että feature.name (kohde.nimi)-kenttää ei näytetä, jos se on none.
- Kuvassa näkyvä alempi none: Muutetaan sellaiseksi, että jos feature.name on none, näytetään feature.fid (kohde.tunnus). Rivi siis jätetään tosin kuin C-kohdassa.
![image](https://user-images.githubusercontent.com/33342290/53078434-e3d06880-34fc-11e9-988f-a34c4c3beac4.png)

**Comment by silenatte** [comment]
Vielä löytyi 885 kpl raportteja, joissa näkyy None:a. Esimerkiksi /ltj/feature-observations-report/133721/
Tällä queryllä löytyy läjä kyseisiä raportteja: /admin/nature/feature/?fid__isnull=true&name__isnull=true

**Comment by otiala** [comment]
@silenatte Päivitetty. Otettu huomioon tilanteet, joissa `feature.fid` on tyhjä.
