### ISSUE TITLE
1 / Raporttien säädöstiedon muokkaus

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#201]
Lajisäädösraportissa ja Lajiraportissa olevan Säädökset-osion https://github.com/City-of-Helsinki/ltj/blob/master/nature/templates/nature/reports/stubs/species-regulation.html
muutostarpeet alla A ja B

Lajisäädösraportti: https://ltj.dev.hel.ninja/ltj-dev/ltj/species-regulations-report/11050/
Lajiraportti: https://ltj.dev.hel.ninja/ltj-dev/ltj/species-report/11050/

A) 
Kommentti koskee tyhjän kentän näyttämistä. Nyt ne näkyvät none-sisältöisenä. Tällaisia kenttiä on nyt aika paljon (myös tässä issuessa https://github.com/City-of-Helsinki/ltj/issues/200 ja varmaan tulee lisää), **saisikohan ne jotenkin systemaattisemmin pois.**

Tarvitaan sellainen muutos, että regulation.paragraph -kenttää ja sitä edeltävää pilkkua ei näytetä, jos regulation.paragraph on none 
 
![image](https://user-images.githubusercontent.com/33342290/53083816-3f542380-3508-11e9-9a1f-58b4cae556ed.png)

B) Samaan säädökset-elementtiin liittyvä toinen isompi muutos.
Läheskään joka säädöksellä ei ole linkki-kentässä urlia, joten tämänhetkinen toteutus jossa joka säädöksellä on linkki, ei ole hyvä, koska suuri osa linkeistä ei nyt toimi. Lisäksi tarvitaan lisätietokenttä, ja toisaalta voimaantulokenttä ei ole tarpellinen. Tarvittavat muutokset kuvattu tässä:

Lajisäädösraportin SÄÄDÖKSET-osion kentät pitäisi laittaa kuten nykyisessä raportissa https://kartta.hel.fi/applications/LTJ/reports/lajiraportti.aspx?id=11050

Eli:
![image](https://user-images.githubusercontent.com/33342290/53087722-7cbcaf00-3510-11e9-81f6-0b0845cd5966.png)

**Comment by silenatte** [comment]
Toteutus vastaa issuen speksiä, joten hyväksyn pendaavan pull requestin, mutta speksiin itseensä kommentti:

"Linkin nimeksi _Linkki_"
Eikö linkin nimi voisi olla vain itse lopullinen linkki? Otsikossahan lukee jo että kyseessä on linkki, lisäksi käyttäjä näkisi suoraan, että minne kyseinen linkki johtaa.

**Comment by SannaElijoki** [comment]
Vain muutamat linkeistä ovat selkeitä ja linkkinimenä käytännöllisiä, esim. http://www.finlex.fi , tämäkin ehkä http://ec.europa.eu/environment/nature/legislation/habitatsdirective/index_en.htm

Mutta suurin osa on tosi pitkiä ja siinä mielessä raportissa käyttäjäepäystävällisiä, kuten https://helda.helsinki.fi/bitstream/handle/10138/159434/Suomen_nisakkaiden_uhanalaisuus_2015.pdf?sequence=3
http://kartta.hel.fi/Applications/ltj/html/linkitetyt_ltj/Helsingin%20uhanalaiset/HelsinginUhanalaiset121202.htm

Mutta pidän ehdotuksen mielessä ja katson jos joskus myöhemmin muutetaan ehdotuksesi mukaiseksi.

**Comment by silenatte** [comment]
Hmm, joo. CSS:llä saa kyllä maksimipituuden, eli loppu osa piiloitetaan. Sitten jos tosi hifistellä haluaa, niin kustakin linkistä voisi parsia vain tuon domain-osan, ja näyttää 3 pistettä linkin jatkumisen merkiksi, esimerkiksi: "https://helda.helsinki.fi/..." ja "https://kartta.hel.fi/...". Näkee vain että mihin palveluun linkki johtaan.
