### ISSUE TITLE
1. Django-päivitys

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#207]
Django-version päivitys uusimpaan 2.1.x -versioon.

https://requires.io/github/City-of-Helsinki/ltj/requirements/?branch=master

**Comment by SannaElijoki** [comment]
Masterissa ei ole vielä Django-päivitystä  https://requires.io/github/City-of-Helsinki/ltj/requirements/?branch=master    (täällä on https://requires.io/github/City-of-Helsinki/ltj/requirements/?branch=feature%2F207-update-django)

**Comment by otiala** [comment]
requires.io on päivittänyt tietonsa, suljen issuen.
