### ISSUE TITLE
1. Lajiraportti ja Havaintosarjaraportti  / title, copyright-merkki pois ja none-teksti pois

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#215]
Linkkejä:
Lajiraportti: https://ltj.dev.hel.ninja/ltj-dev/ltj/species-report/10256/
Havaintosarjaraportti: https://ltj.dev.hel.ninja/ltj-dev/ltj/observationseries-report/501/
Raporttikoodit: https://github.com/City-of-Helsinki/ltj/tree/master/nature/templates/nature/reports

**A) Lajiraportin ja Havaintosarjaraportin titleen** tarvitaan user_role -merkintä vastaavasti kuin on esim. kohderaportissa.
![image](https://user-images.githubusercontent.com/33342290/54670619-b4614b80-4afc-11e9-876b-d220e4118900.png)

Muissa raporteissa tämä on.

**B) Lajiraportti ja Havaintosarjaraportti: Raportin alaosasta © -merkki pois**. Sen yhteydessä olevat tekstit jäävät.
![image](https://user-images.githubusercontent.com/33342290/54670820-2f2a6680-4afd-11e9-9a14-38f2b0e5ebb9.png)

**C) Lajiraportin alalajin species.name_subspecies_1** kohdalle tulee nyt none silloin kuin alalajia ei ole. None pitää ottaa pois. 
![image](https://user-images.githubusercontent.com/33342290/54670346-22f1d980-4afc-11e9-9052-a26667437e69.png)

**Comment by otiala** [comment]
Tähän issueen viittaavassa PR:ssä on tehty kaikki, paitsi A-kohdan havaintosarjaraportin otsikkoon user_rolen lisääminen. Jostain syystä `ObservationSeriesReportView` ei peri `ProtectedReportViewMixin`iä, joka lisää `user_role` tiedon templaattikontekstiin. Selvitetään, onko tämä jätetty tarkoituksella perimättä.
