### ISSUE TITLE
1. HMAC-tunnistautumiseen virheilmoitusten lisääminen

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#235]
HMAC-tunnistautumiseen liittyen tarvitaan mahdollisten ilmaantuvien vikojen huomaamiseen ja selvittämiseen ilmoituksia ja http-virhekoodeja. Djangon pää siis antaisi virheilmoituksen  jos  HMAC-protokollassa on sen mielestä ongelmia. Tällä hetkellä taitaa olla niin, että vaikka headereissa on "X-Forwarded-Groups: ltj_admin", niin Django näyttää julkisen version, jos protokollassa on virhe. Käytössä on hankala huomata, että on väärä raporttiversio.

**Comment by SannaElijoki** [comment]
Huom. Parhaillaan ja muutaman viikon ajan käynnissä on uuden LTJ-kannan ja raporttien (tunnistautumisineen) integroinnin testaus testi-Karttapalvelussa.
Näin ollen tarvitaan tieto tilanteesta, jossa issuen toteutus mahdollisesti aiheuttaa katkoksia tunnistautumisessa.

**Comment by vikoivun** [comment]
Tässä voi pistää vaikka 403 ja "Invalid Authorization" tekstiksi.

**Comment by SannaElijoki** [comment]
Toteutettu. (https://github.com/City-of-Helsinki/ltj/pull/260)
