### ISSUE TITLE
1. Admin login / AD-integration

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#237]
AD-integration to admin site login, using Tunnistamo. 
(See Riku´s comments below)

**Comment by Rikuoja** [comment]
Requires OAuth2 support for the API (or at least for the admin site, if not all of the API). Implemented e.g. for respa in. https://github.com/City-of-Helsinki/respa/blob/master/respa_admin/views/_login.py , so you can look for an example implementation there.

**Comment by Rikuoja** [comment]
Ah. LTJ doesn't use our custom user model https://github.com/City-of-Helsinki/django-helusers yet.

So the easiest way to get this is to move the LTJ user model to our https://github.com/City-of-Helsinki/django-helusers user model, which supports JWT tokens, authentication and such.

**Comment by Rikuoja** [comment]
Basically, this ties very much to the whole JWT and API user management issue. So if we implement this, we have implemented basic JWT support for the API as well, as they all come in the same django-helusers package.

Then it is easier to implement different levels of non-public REST API in the future.

**Comment by frwickst** [comment]
From the kick-off meeting:
- The AD groups to be used will be delivered from @SannaElijoki
