### ISSUE TITLE
1. Fixing admin shapefile import error

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#267]
Admin shape-file import is not working any more and should be fixed.
Any run ends to error:

-----
![image](https://user-images.githubusercontent.com/33342290/90747758-000fba00-e2da-11ea-9502-5f49998c53db.png)
-----
Additional information in Oskari´s comment below. 

Testing for example with shapetesti_1.zip, which will be mailed when needed.

Validity checkes seems to work fine. I.e. notice when feature class missing, extra attributes or missing file.

**Comment by otiala** [comment]
Debug-tilassa Django antaa virheilmoituksen:

```GEOSException at /admin/imports/shapefileimport/add/
Error encountered checking Geometry returned from GEOS C function "GEOSWKTReader_read_r".```

**Comment by frwickst** [comment]
From the kick-off meeting:
- This is failing for all shapefiles
- This might have started to break as part of some update in the past (could have been a Django update)
