### ISSUE TITLE
1. Kohderaportin viilauksia  (PR)

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#271]
https://github.com/City-of-Helsinki/ltj/pull/270  katselmontitarve

Kohderaportin viivoja on säädetty aikaisemminkin, mutta sinne on vielä jäänyt puutteita tai tuplaviivoja raportin sisällöstä riippuen. Koitin nyt laittaa niin, että joka elementin jälkeen on viiva. 

Lisäksi laitettu kohdelinkit avautumaan omaan ikkunaan.

**Comment by otiala** [comment]
Hyvältä näyttää. Katselmoitu ja mergetty.
