### ISSUE TITLE
1. Admin map / Change WFS-layers

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#283]
(https://github.com/City-of-Helsinki/ltj/blob/master/nature/static/nature/js/NatureOLMapWidget.js)

WFS-layers in Admin feature form's map should be changed to these:

From http://apila.hel.fi/gis/hel/wfs   (Intranet)

featureWFSLayers:

['LTJ_virka_rauhoitettu_luonnonsuojelualueet', 'Luonnonsuojelualueet'],
['LTJ_virka_rauhoitettu_Natura_aluemaiset', 'Natura-alueet (aluemaiset)'],
['LTJ_virka_rauhoitettu_Natura_viivamaiset', 'Natura-alueet (viivamaiset)'],
['LTJ_virka_rauhoitettu_suojellut_luontotyypit', 'Suojellut luontotyypit'],
['LTJ_virka_rauhoitettu_luonnonmuistomerkit', 'Luonnonmuistomerkit'],
['LTJ_virka_rauhoitettu_suojellut_lajikohteet','Suojellut lajikohteet'],
['LTJ_virka_rauhoitettavat_luonnonsuojeluohjelma', 'Luonnonsuojeluohjelman kohteet'],
['LTJ_virka_arvokkaat_kasvikohteet', 'Arvokkaat kasvikohteet'],
['LTJ_virka_arvo_tarkeat_lintualueet', 'Tärkeät lintualueet'],
['LTJ_virka_arvo_tarkeat_lepakkoalueet', 'Tärkeät lepakkoalueet'],
['LTJ_virka_arvokkaat_geologiset_aluemaiset', 'Arvokkaat geologiset kohteet (aluemaiset)'],
['LTJ_virka_arvokkaat_geologiset_viivamaiset', 'Arvokkaat geologiset kohteet (viivamaiset)'],
['LTJ_virka_arvo_tarkeat_matelija_ja_sammakkoelainkohteet', 'Tärkeät matelija- ja sammakkoeläinkohteet'],
['LTJ_virka_arvo_kaapakohteet', 'Kääpäkohteet'],
['LTJ_virka_arvo_metsakohteet', 'Metsäkohteet'],
['LTJ_virka_arvo_liito_orava_ydinalueet', 'Liito-oravan ydinalueet'],
['LTJ_virka_arvo_liito_orava_elinalueet', 'Liito-oravan elinalueet'],
['LTJ_virka_arvo_lahokaviosammal_elinymparistot', 'Lahokaviosammalen elinympäristöt'],
['LTJ_virka_arvo_lahokaviosammal_tukialueet', 'Lahokaviosammalen tukialueet'],
['LTJ_virka_perinnemaisemat', 'Perinnemaisemia'],
['LTJ_virka_luontotyypit_uhanalaiset', 'Uhanalaiset luontotyypit'],
['LTJ_virka_vesi_purot', 'Purot'],
['LTJ_virka_vesi_lammet', 'Lammet'],
['LTJ_virka_vesi_purojen_putkitetut_osuudet', 'Purojen putkitetut osuudet'],
['LTJ_virka_vesi_kunnostetut_purokohdat', 'Kunnostetut purokohdat'],
['LTJ_virka_vesi_purojen_ja_lampien_valuma_alueet', 'Purojen ja lampien valuma-alueet'],
['LTJ_virka_vesi_lahteet', 'Lähteet'],
['LTJ_virka_vesi_vesikasvilinjat', 'Vesikasvilinjat'],
['LTJ_virka_vesi_vedenalainen_roskaantuminen', 'Vedenalainen roskaantuminen'],
['LTJ_virka_luontotyypit_biotooppiaineisto', 'Biotooppiaineisto'],
['LTJ_virka_muu_elainhavaintoja', 'Eläinhavaintoja '],
['LTJ_virka_muut_luontokohteet', 'Muut luontokohteet'],
['LTJ_virka_ekologiset_yhteydet_2015', 'Ekologiset yhteydet 2015'],
['LTJ_virka_metsaverkosto_2015', 'Metsäverkosto 2015'],
['LTJ_virka_luontoselvityksia', 'Luontoselvityksiä'],

Most of the layers are polygons/multipolygons, but some are lines/multilines or points.

Screen shot from current list of WFS-layers below. (Layers are not set to work).

![image](https://user-images.githubusercontent.com/33342290/90647097-a1e2c880-e240-11ea-84e3-9b7d4f0bacf2.png)

**Comment by frwickst** [comment]
From the kick-off meeting:
- @SannaElijoki will deliver the layer names and other information regarding the open data that can be used for this so that the intranet does not have to be used.

**Comment by SannaElijoki** [comment]
Finally Intranet layers listed in issue text should be used, but it may be better to first try with these open data layers.
(There are less layers in open data, and some of the features are filtered) 

LTJ open WFS layers in https://kartta.hel.fi/ws/geoserver/avoindata/wfs  

LTJ_avoin_arvo_kaapakohteet
LTJ_avoin_arvo_lahokaviosammal_elinymparistot
LTJ_avoin_arvo_lahokaviosammal_tukialueet
LTJ_avoin_arvo_liito_orava_elinalueet
LTJ_avoin_arvo_liito_orava_ydinalueet
LTJ_avoin_arvo_tarkeat_lepakkoalueet
LTJ_avoin_arvo_tarkeat_lintualueet
LTJ_avoin_arvo_tarkeat_matelija_ja_sammakkoelainkohteet
LTJ_avoin_arvokkaat_geologiset_aluemaiset
LTJ_avoin_arvokkaat_geologiset_viivamaiset
LTJ_avoin_arvokkaat_kasvikohteet
LTJ_avoin_ekologiset_yhteydet_2015
LTJ_avoin_luontotyypit_biotooppiaineisto
LTJ_avoin_metsaverkosto_2015
LTJ_avoin_muu_elainhavaintoja
LTJ_avoin_muut_luontokohteet
LTJ_avoin_rauhoitettavat_luonnonsuojeluohjelma
LTJ_avoin_rauhoitettu_luonnonmuistomerkit
LTJ_avoin_rauhoitettu_luonnonsuojelualueet
LTJ_avoin_rauhoitettu_Natura_aluemaiset
LTJ_avoin_rauhoitettu_Natura_viivamaiset
LTJ_avoin_rauhoitettu_suojellut_luontotyypit
LTJ_avoin_vesi_lahteet
LTJ_avoin_vesi_lammet
LTJ_avoin_vesi_purojen_ja_lampien_valuma_alueet
LTJ_avoin_vesi_purot

**Comment by SannaElijoki** [comment]
Open Data WFS layers are working fine! I close this issue, and will change these to Intranet WFS-connection and -layers later (when topical).
