### ISSUE TITLE
2. Handle invalid HMAC authentication

### ISSUE THREAD

**Issue by SannaElijoki** [City-of-Helsinki/ltj#291]
Add notifications when there is something wrong with authentication.

(See also https://github.com/City-of-Helsinki/ltj/pull/260)

**Comment by vikoivun** [comment]
Loggin through Python logging would be needed here as well. It might be just a configuration issue, as it seems the code referenced already raises a "PermissionDenied"-exception. Maybe that is already hooked to the logging?

Essentially we need a message logged using logging when PermissionDenied is raised.

**Comment by vikoivun** [comment]
Specifically a message is needed that prints out:
* IP-address
* operation being attempted
also the exception should be passed to sentry as that is our only way to generate alerts at the moment.
