### ISSUE TITLE
Use Finnish for the admin interface

### ISSUE THREAD

**Issue by frwickst** [City-of-Helsinki/ltj#37]
User story:
> As an admin I want that finally the interface is Finnish.

We already have the Finnish words for most of the things in the code, the main thing that needs to be translated are the tooltips.

**Comment by mingfeng** [comment]
Closed the issue now.

Default languge set to Finnish in PR: https://github.com/City-of-Helsinki/ltj/pull/60, and we have separate ticket for tooltips, see details in: #52
