### ISSUE TITLE
Show other features from Luontotietojärjestelmä when editing features

### ISSUE THREAD

**Issue by mingfeng** [City-of-Helsinki/ltj#39]
As an admin I want to select other features from Luontotietojärjestelmä to be visible on the map so that I can digitalize  correctly. Features are to be read into system from WFS API (official version, not public version). All the layers enabled through API are needed.

**Comment by mingfeng** [comment]
@SannaElijoki Have we setup the WFS server for the features? What is the url?

**Comment by SannaElijoki** [comment]
Riku was going to create new WFS-username for app use, but now I reminded that the username we now have is not named personally for me so you can use it. 
http://geoserver.hel.fi/geoserver/wfs  
username: ltj
password: liito-orava

In the same address there are also open data LTJ-layers "ltj_avoin..", do not use them. Use other layers starting "ltj_". I just counted that there are 23 layers.

**Comment by frwickst** [comment]
@SannaElijoki Do note that this reposotiry is open everyone. Are those credentials secret in any way?

**Comment by mingfeng** [comment]
We need to setup a WFS server that uses the same database as the application for the features.
