### ISSUE TITLE
Add uri field to lajihavainto

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/ltj#4]

**Comment by Rikuoja** [comment]
Similar to already existing "koodi" in lajirekisteri.

**Comment by Rikuoja** [comment]
Both these fields are for lajitietokeskus URI identifiers.

**Comment by mingfeng** [comment]
Can this field be blank and unique? if not, what default value should be provided?

**Comment by SannaElijoki** [comment]
Can be blank (since we add values to every line and start exchanging data with laji.fi, hopefully next year).
Non-blank values should be unique, but that may be in conflict with several blanks, so don´t have to be unique (yet.)

**Comment by Rikuoja** [comment]
I guess the default must be blank then, because the URI should be unique for every observation.

**Comment by Rikuoja** [comment]
Essentially, this is giving each observation a duplicate id (the same way as koodi does in the species model already).

However, this cannot be really avoided, because the species and observations must have unique national URIs in the future, and we don't yet know what their URIs will be because https://laji.fi/en (Finnish Biodiversity Info Facility) will determine these unique URIs.

**Comment by mingfeng** [comment]
What would be the possible schemas for uri, for example: `uri://`,  `http://` or something else? We need this information because Django has a `URLField` which will do necessary validations on the given `uri`, but if we don't know yet, I think we should then use a normal `CharField`

**Comment by SannaElijoki** [comment]
http://
From http://schema.laji.fi/class/MY.collection   "The full URI of each property is defined by a prefix http://tun.fi/ followed by the class name. For example, the URI of the MY.notes is http://tun.fi/MY.notes."
