### ISSUE TITLE
Change Mobility model name to LocalOrMigrating

### ISSUE THREAD

**Issue by frwickst** [City-of-Helsinki/ltj#40]
User story:
> As an   admin I want that Mobility-table is renamed to LocalOrMigrating

Note: If there is a better word for then `LocalOrMigrating` then use that.

**Comment by frwickst** [comment]
@SannaElijoki I'll repeate this here since the Slack channel is currently quite cluttered.

I feel like `LocalOrMigrating` is a really bad name for the model since it sounds like it is one of the other, which it is not since there are three values that the `value` field can have. The name `MigrationClass` or maybe `MigratoryClass` (if that is more proper) corresponds more closely to the Finnish name of the table that was in the Oracle database `liikkumislk` (where I guess `lk` == `luokka`).

**Comment by SannaElijoki** [comment]
You are right!! I prefer MigrationClass
