### ISSUE TITLE
Add django admin pages for different registers

### ISSUE THREAD

**Issue by mingfeng** [City-of-Helsinki/ltj#41]
As an admin I want that application can modify also Transaction register (now named Event register), Habitat type register, Regulations register, Value-register and Person-register. (So far it modifies Feature classes, Features, Link types, Observation series, Publications, Species)   NOTICE! Due to datasecurity reasons only Admin can have view and edit rights for person-register. Currently this person is Sanna Elijoki.  So e.g. potential test users cannot have this right.

**Comment by SannaElijoki** [comment]
Habitat types:
list_display = ('id', 'name', 'code', 'group')
search_fields = ('id', 'name', 'code', 'group', 'lisatieto')
list_filter = ('group')

Regulations:
list_display = ('id', 'name', 'paragraph', 'value', 'value_explanation', 'valid')
search_fields = ('id', 'name', 'value', 'value_explanation')
list_filter = ('valid', 'name')

Values:
list_display = ('id', 'value_type', 'explanation')
search_fields = ('id', 'value_type', 'explanation')
_no filters_

Transactions:
list_display = ('id', 'transaction_type', 'description', 'protection_level_id')
search_fields = ('id', 'description')
list_filter = ('protection_level_id')

Persons:
list_display = ('id', 'surname', 'first_name')
search_fields = ('id', 'surname', 'first_name')
_no filters_

**Comment by SannaElijoki** [comment]
Habitat types:
list_display = ('id', 'name', 'code', 'group')
search_fields = ('id', 'name', 'code', 'group', 'lisatieto')
list_filter = ('group')

Regulations:
list_display = ('id', 'name', 'paragraph', 'value', 'value_explanation', 'valid')
search_fields = ('id', 'name', 'value', 'value_explanation')
list_filter = ('valid', 'name')

Values:
list_display = ('id', 'value_type', 'explanation')
search_fields = ('id', 'value_type', 'explanation')
_no filters_

Transactions:
list_display = ('id', 'transaction_type', 'description', 'protection_level_id')
# 'transaction_type' here means field 'name' from TransactionType.
# description is 255 long , which may cause some trouble to display.
search_fields = ('id', 'description')
list_filter = ('protection_level_id')

Persons:
list_display = ('id', 'surname', 'first_name')
search_fields = ('id', 'surname', 'first_name')
_no filters_

**Comment by SannaElijoki** [comment]
Habitat types:
list_display = ('id', 'name', 'code', 'group')
search_fields = ('id', 'name', 'code', 'group', 'lisatieto')
list_filter = ('group')

Regulations:
list_display = ('id', 'name', 'paragraph', 'value', 'value_explanation', 'valid')
search_fields = ('id', 'name', 'value', 'value_explanation')
list_filter = ('valid', 'name')

Values:
list_display = ('id', 'value_type', 'explanation')
search_fields = ('id', 'value_type', 'explanation')
no filters

Transactions:
list_display = ('id', 'transaction_type', 'description', 'protection_level_id')
NOTE: 'transaction_type' here means field 'name' from TransactionType.
NOTE: description is 255 long , which may cause some trouble to display.
search_fields = ('id', 'description')
list_filter = ('protection_level_id')

Persons:
list_display = ('id', 'surname', 'first_name')
search_fields = ('id', 'surname', 'first_name')
no filters
